export {
  initStorage,
  getDb,
  getUserById,
  getUserByGithubId,
  getUserByEmail,
  createUserFromGithub,
  updateLastLogin,
  getCredits,
  consumePages,
  addPages,
  createTask,
  getTask,
  updateTask,
  getUserTasks,
} from "./firestore.js";
